-- About ページの略歴（Timeline）
-- 日付は year + month で持つ。年だけ分かる場合は month を NULL にする
-- (year / month は H2 予約語なので event_year / event_month にしてある)
CREATE TABLE timeline_events (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_year  INT          NOT NULL,
    event_month INT,
    title       VARCHAR(200) NOT NULL,
    description TEXT,
    sort_order  INT          NOT NULL DEFAULT 0,
    published   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 初期サンプル。後で管理画面から差し替える想定
INSERT INTO timeline_events (event_year, event_month, title, description, sort_order) VALUES
    (2018, 3, '高校卒業',          NULL,                                                       1),
    (2018, 4, '大学入学',          '情報系の学部に入学',                                       2),
    (2020, 7, '長期インターン参加', 'Webアプリ開発のスタートアップで Spring Boot を使い始める', 3),
    (2022, 3, '大学卒業',          NULL,                                                       4);
