-- 作品（ポートフォリオに載せるプロジェクト一覧）
CREATE TABLE works (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    summary     VARCHAR(500),
    description TEXT,
    url         VARCHAR(500),
    tags        VARCHAR(300),
    sort_order  INT          NOT NULL DEFAULT 0,
    published   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
