-- 管理画面からアップロードする画像（顔写真など）を DB に保存する
CREATE TABLE media_files (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename     VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes   BIGINT       NOT NULL,
    data         BLOB         NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
