-- スキル一覧。カテゴリで括れるようにしてある
CREATE TABLE skills (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category   VARCHAR(50)  NOT NULL,
    name       VARCHAR(100) NOT NULL,
    sort_order INT          NOT NULL DEFAULT 0,
    published  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- sort_order でカテゴリの並び順も決められるよう、カテゴリごとに 1, 11, 21 ... のように区切ってある
INSERT INTO skills (category, name, sort_order) VALUES
    ('Languages',     'Java',         1),
    ('Languages',     'TypeScript',   2),
    ('Languages',     'Python',       3),
    ('Languages',     'Go',           4),
    ('Frameworks',    'Spring Boot', 11),
    ('Frameworks',    'React',       12),
    ('Frameworks',    'Vue 3',       13),
    ('Frameworks',    'Next.js',     14),
    ('Tools & Infra', 'Docker',      21),
    ('Tools & Infra', 'AWS',         22),
    ('Tools & Infra', 'PostgreSQL',  23),
    ('Tools & Infra', 'Cloudflare',  24);
